### ISSUE TITLE
CFBundleVersion is blank…

### ISSUE THREAD

**Issue by schwa** [mattgallagher/CwlSignal#10]
If you build CwlSignal via directly via Xcode, using instructions in CwlSignal's README (or xcodebuild or Carthage and/or Punic) the CFBundleVersion in the built product Info.plist is blank. In the project the CFBundleVersion is defined as "$(CURRENT_PROJECT_VERSION)" which obviously isn't getting populated.

iTunes Connect will reject any framework with a missing CFBundleVersion.

**Comment by mattgallagher** [comment]
Thanks for pointing this out. It looks like that value got lost when I merged with the swift-package generated project file in this commit: 14cc6d68b8d6b4a6f9a7c91aa0d8f97023c7beb4

Oops.

Fix is in latest commit: 7f4ebe52ca3fb2593990d0dce5d283fccf97c721
