### ISSUE TITLE
Library not loaded: @rpath/CwlUtils.framework/CwlUtils

### ISSUE THREAD

**Issue by andreyz** [mattgallagher/CwlSignal#11]
After updating to latest master 0d31f45e224e0d09bfc01be28729fee2fe2b7d8c build for device crashes due to `image not found` error.

**Comment by mattgallagher** [comment]
I've added the following instructions to the bottom of README.md file. I hope it explains what has happened and what you need to do.

## Additional steps for latest CwlSignal 2.0.0-beta builds on master

The latest master versions (including builds tagged 2.0.0-beta.1 and 2.0.0-beta.2) no longer copy the CwlUtils.framework inside the CwlSignal.framework. This avoids duplicate inclusion of the framework and other potential problems but it means that you need to copy CwlUtils.framework into your build as part of your Copy Files (Frameworks) build phase (in the same way that you're already copying the CwlSignal.framework).

To copy the CwlUtils.framework, expand the CwlSignal.xcodeproj -> Dependencies folder. You should see three frameworks there. They may be red (depending on whether you've build the Mac debug build) but that doesn't matter. Drag the CwlUtils.framework onto the Copy Files (Frameworks) build phase where you've already got CwlSignal.framework. You don't need the other two frameworks (they're used by the CwlSignal testing target, not the main build).
