### ISSUE TITLE
frameworks trigger warning about not being safe in an extension

### ISSUE THREAD

**Issue by sleifer** [mattgallagher/CwlSignal#15]
Using 2.0.0-beta.15, both CwlSignal and CwlUtil trigger the 'linking against a dylib which is not safe for use in application extensions' warning when being linked into an iMessage extension. Are they in fact not safe for use in extensions, or could 'Require Only App-Extension-Safe API' be set in the framework projects so that Xcode knows everything is good to go?

**Comment by mattgallagher** [comment]
CwlSignal 2.0.0-beta.18 and CwlUtils 1.1.0-beta.13 have added the build setting `APPLICATION_EXTENSION_API_ONLY = YES` to the iOS targets. It should resolve the problem.
