### ISSUE TITLE
Executing test target fails because of development team id

### ISSUE THREAD

**Issue by Soryu** [mattgallagher/CwlSignal#17]
Hi, I’m trying to execute the test target on macOS. Both Xcode 8 and 9b4 fail, it seems like your personal development team ID is hardcoded in both the local project files and the downloaded dependencies. Do the tests run for you on a vanilla machine/user account?
I might be doing something wrong, though, the whole dependency download and test build chain is quite involved and too clever for me.

```
No signing certificate "Mac Development" found:  No "Mac Development" signing certificate matching team ID "S7YQ892G6G" with a private key was found.
```

**Comment by andreyz** [comment]
@Soryu, you can just set "no signing" in build settings for each of the targets that cause the error and it'll resolve your issues.

**Comment by andreyz** [comment]
@mattgallagher with last few commits some of your targets include signing build settings, just FYI

**Comment by Soryu** [comment]
@andreyz Have you actually tried it? How could I possibly disable it in targets that are downloaded as part of the build process?

**Comment by mattgallagher** [comment]
Sorry about the signing settings. I've stripped them from all of CwlSignal, CwlUtils, CwlPreconditionTesting and CwlCatchException so there shouldn't be any problem with either CwlSignal or any of the dependencies that it pulls in.
