### ISSUE TITLE
Undeclared type 'Cancellable'?

### ISSUE THREAD

**Issue by stevenbedrick** [mattgallagher/CwlSignal#18]
I'm probably missing something very obvious, but when I try and install CwlSignal with Carthage, I'm getting many compilation errors (from Carthage's xcodebuild log) complaining about the use of the `Cancellable` type, for example: 

```
CwlSignal/CwlSignal.swift:1226:50: error: use of undeclared type 'Cancellable'
public final class SignalInput<T>: SignalSender, Cancellable {
                                                 ^~~~~~~~~~~
```

I did some digging in the CwlSignal source, and I can't actually see where that type is declared. Is there some other dependency I should make sure to include first, or something? Or am I just being dense? Any help would be most appreciated. Thanks!

**Comment by mattgallagher** [comment]
`Cancellable` is defined in CwlUtils.framework. This framework should be fetched and built correctly by Carthage.

```
Matthews-MacBook-Air:CarthageTest matt$ carthage update
*** Cloning CwlSignal
*** Cloning CwlUtils
*** Checking out CwlUtils at "1e737c9799066b302907a435f7ed3a16b835a8d5"
*** Checking out CwlSignal at "6b080bc7e4505a83b8e07d999bc4349585b6fbfa"
*** xcodebuild output can be found in /var/folders/4r/zl51mt6s7_3_r17w83v03zym0000gn/T/carthage-xcodebuild.2q0BRe.log
*** Building scheme "CwlUtils_macOS" in CwlUtils.xcodeproj
*** Building scheme "CwlUtils_iOS" in CwlUtils.xcodeproj
*** Building scheme "CwlSignal_macOS" in CwlSignal.xcodeproj
*** Building scheme "CwlSignal_iOS" in CwlSignal.xcodeproj
```

Are you building the latest master? That's what I tested and it's working. It's possible if you're building an earlier version that the build process might not be searching Carthage directories correctly - I recommend the latest master (2.0.0-beta.35).

**Comment by torinkwok** [comment]
@stevenbedrick I've encountered the totally same issue and fixed it by always checking out the latest beta branch in `Package.swift`:

```swift
import PackageDescription

let package = Package(
    name: "CwlSignalLab"
  , dependencies: [
      .Package(
          url: "https://github.com/mattgallagher/CwlSignal.git"
        , versions: Version( 2, 0, 0, prereleaseIdentifiers: [ "beta" ] )..<Version( 2, .max, .max, prereleaseIdentifiers: [ "beta" ] )
      )
    ]
  )
```
Seems that's mainly because prior to version 2.0 beta, there was no such a seamless integration between __CwlSignal__ itself and those external libraries (__CwlCatchException__, __CwlPreconditionTesting__ and __CwlUtils__) on which __CwlSignal__ depends.

> I did some digging in the CwlSignal source, and I can't actually see where that type is declared.

[`Cancellable` protocol](https://github.com/mattgallagher/CwlUtils/blob/master/Sources/CwlUtils/CwlCancellable.swift) is defined in __CwlUtils__.

**Comment by stevenbedrick** [comment]
Aha! Yes, the problem is that I apparently do not know how to follow instructions, and was using Carthage incorrectly- it was pulling the wrong version down from Github. Thank you very much!
