### ISSUE TITLE
Archiving produces invalid package

### ISSUE THREAD

**Issue by andreyz** [mattgallagher/CwlSignal#27]
<img width="237" alt="screenshot 2018-09-26 at 07 41 19" src="https://user-images.githubusercontent.com/205317/46059451-92939700-c15f-11e8-88b4-e5bfd1a117e2.png">

Seems that CwlUtils.framework shouldn't be placed there.

**Comment by andreyz** [comment]
Maybe I'll switch to just including concatenated version of CwlSignal and CwlUtils in my project instead of using it as a sub-project.

**Comment by andreyz** [comment]
Statically including CwlSignal allowed me to sidestep the issue. Feel free to ignore or postpone reacting to it. Thanks again for great work on the library.

**Comment by mattgallagher** [comment]
The framework targets for CwlUtils.framework had the SKIP_INSTALL build setting set to NO. The correct setting should be YES. I've fixed this in the latest commit. Thanks for pointing this out.
