### ISSUE TITLE
Lastest commits in CwlUtils are breaking CwlSignal current version

### ISSUE THREAD

**Issue by xjki** [mattgallagher/CwlSignal#29]
As you did not have published CwlSignal and CwlUtils as CocoaPods public pod, people currently can only point to your github repo if they want to use CwlSignal.

Unfortunately with direct github links you cannot specify version of the pod. Lastest changes in CwlUtils (after Oct25, 2018/2.0 tag) therefore are breaking current CwlSignal pod.

It would be good idea to push stable releases of the CwlUtils and CwlSignal pods to CocoaPods specs repo to let people use stable builds with specified version. See:
https://guides.cocoapods.org/making/getting-setup-with-trunk

**Comment by mattgallagher** [comment]
Thanks for alerting me to this. I'll sort it out this weekend.

**Comment by mattgallagher** [comment]
Hi @xjki , I've pushed the podspecs for CwlSignal tag 2.1 and CwlUtils tag 2.1 to CocoaPods so you should be able to use with:

```
pod 'CwlSignal', '~> 2.1'
pod 'CwlUtils', '~> 2.1'
```

Let me know if there are any further problems.

**Comment by xjki** [comment]
It's perfect. Thanks!
