### ISSUE TITLE
Carthage Support

### ISSUE THREAD

**Issue by Ashton-W** [mattgallagher/CwlSignal#3]
Pleased to say **CwlSignal** supports [Carthage](https://github.com/Carthage/Carthage) already.

However, it generates the following binaries:

```
Carthage/
└── Build
    ├── Mac
    │   ├── CwlCatchException.framework
    │   ├── CwlCatchException.framework.dSYM
    │   ├── CwlPreconditionTesting.framework
    │   ├── CwlPreconditionTesting.framework.dSYM
    │   ├── CwlSignal.framework
    │   ├── CwlSignal.framework.dSYM
    │   ├── CwlUtils.framework
    │   └── CwlUtils.framework.dSYM
    ├── iOS
    │   ├── CwlCatchException.framework
    │   ├── CwlCatchException.framework.dSYM
    │   ├── CwlPreconditionTesting.framework
    │   ├── CwlPreconditionTesting.framework.dSYM
    │   ├── CwlSignal.framework
    │   ├── CwlSignal.framework.dSYM
    │   ├── CwlUtils.framework
    │   └── CwlUtils.framework.dSYM
    └── tvOS
        ├── CwlPreconditionTesting.framework
        └── CwlPreconditionTesting.framework.dSYM
```

Unfortunately **Carthage** will build the schemes in all projects it finds, including the CwlUtils. Users of this framework only actually need `CwlSignal.framework`.

We could document this fact for Carthage users. I don't know of a way to control what Cathage builds. Thoughts?

**Comment by mattgallagher** [comment]
Theoretically, I could change the linked CwlUtils subtree over to a dedicated branch that omits the CwlUtils.xcodeproj file and the CwlPrecondition subtree (and by extension CwlCatchException subtree) but I'd need to create such a branch keep it up-to-date over time. I'm hesitant because it's a non-zero amount of maintenance but it wouldn't be impossible.

However, I think it might be a lot easier just to put a note in the ReadMe file.

**Comment by Ashton-W** [comment]
I think another option would be to pull the them down with Carthage (or a directory structure that looks like it), as it will ignore dependencies it pulled down itself.

**Comment by mattgallagher** [comment]
That's the scenario I was trying to *avoid* as it places a git submodule management burden onto non-Carthage users, versus the current subtree arrangement which is ready-to-use immediately on pulling of the CwlSignal repository.

**Comment by Ashton-W** [comment]
I mean use Carthage (or mimick it) with checked in sources, not sub modules. I'll try it out locally

**Comment by Ashton-W** [comment]
Well it works. Moving `CwlUtils/` to `Carthage/Checkouts/CwlUtils/` makes Carthage ignore it.
The command I'm using is `carthage build --no-skip-current` by the way.

```
Carthage/
├── Build
│   ├── Mac
│   │   ├── CwlSignal.framework
│   │   └── CwlSignal.framework.dSYM
│   └── iOS
│       ├── CwlSignal.framework
│       └── CwlSignal.framework.dSYM
└── Checkouts
    └── CwlUtils
        ├── CwlPreconditionTesting
        ├── CwlUtils
        ├── CwlUtils.xcodeproj
        ├── CwlUtilsTests
        ├── CwlUtils_iOSHarness
        ├── CwlUtils_iOSHarnessUITests
        ├── CwlUtils_macOSHarness
        ├── CwlUtils_macOSHarnessUITests
        └── README.md
```

🤕 Whether this is worth doing or not..

https://github.com/Ashton-W/CwlSignal/tree/aw-carthage-workaround

**Comment by mattgallagher** [comment]
Carthage build support is now fully supported (since 2.0.0-beta.18 or something).
