### ISSUE TITLE
Playground: wrong text on "combine" page

### ISSUE THREAD

**Issue by ole** [mattgallagher/CwlSignal#6]
Great library, thanks for sharing!

I've been checking out the playground, and I noticed that the text on the page "Parallel composition - combine" doesn't seem to match the code — it's more or less identical to the text on the "transform" page.

![screen shot 2016-12-08 at 16 29 45](https://cloud.githubusercontent.com/assets/5010/21015797/9219cbf2-bd63-11e6-9a1c-f348c8b9024e.png)

**Comment by mattgallagher** [comment]
I've finally fixed this. Sorry it took so long: 929e81d91560f3f569c251a2dc4381172ed584c6
